// <auto-generated />
namespace SampleWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202006110941546_change_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
